PREFIX cert: <http://www.w3.org/ns/auth/cert#>
PREFIX rsa: <http://www.w3.org/ns/auth/rsa#>

SELECT ?m ?e ?mod ?exp ?person
WHERE {
    [] cert:identity ?person ;
    rsa:modulus ?m ;
    rsa:public_exponent ?e .
    OPTIONAL { ?m cert:hex ?mod . }
    OPTIONAL { ?e cert:decimal ?exp . }
}
